final Map<String, dynamic> apiResponse = {
  "kind": "customsearch#search",
  "url": {
    "type": "application/json",
    "template":
        "https://www.googleapis.com/customsearch/v1?q={searchTerms}&num={count?}&start={startIndex?}&lr={language?}&safe={safe?}&cx={cx?}&sort={sort?}&filter={filter?}&gl={gl?}&cr={cr?}&googlehost={googleHost?}&c2coff={disableCnTwTranslation?}&hq={hq?}&hl={hl?}&siteSearch={siteSearch?}&siteSearchFilter={siteSearchFilter?}&exactTerms={exactTerms?}&excludeTerms={excludeTerms?}&linkSite={linkSite?}&orTerms={orTerms?}&relatedSite={relatedSite?}&dateRestrict={dateRestrict?}&lowRange={lowRange?}&highRange={highRange?}&searchType={searchType}&fileType={fileType?}&rights={rights?}&imgSize={imgSize?}&imgType={imgType?}&imgColorType={imgColorType?}&imgDominantColor={imgDominantColor?}&alt=json"
  },
  "queries": {
    "request": [
      {
        "title": "Google Cfustom Search - cars",
        "totalResults": "267000000",
        "searchTerms": "cars",
        "count": 10,
        "startIndex": 1,
        "inputEncoding": "utf8",
        "outputEncoding": "utf8",
        "safe": "off",
        "cx": "d21ad4f662659e3f8"
      }
    ],
    "nextPage": [
      {
        "title": "Google Custom Search - cars",
        "totalResults": "267000000",
        "searchTerms": "cars",
        "count": 10,
        "startIndex": 11,
        "inputEncoding": "utf8",
        "outputEncoding": "utf8",
        "safe": "off",
        "cx": "d21ad4f662659e3f8"
      }
    ]
  },
  "context": {"title": "Google"},
  "searchInformation": {
    "searchTime": 0.643615,
    "formattedSearchTime": "0.64",
    "totalResults": "267000000",
    "formattedTotalResults": "267,000,000"
  },
  "items": [
    {
      "kind": "customsearch#result",
      "title": "Waymo",
      "htmlTitle": "Waymo",
      "link": "https://www.google.com/selfdrivingcar/",
      "displayLink": "www.google.com",
      "snippet":
          "Waymo—formerly the Google self-driving car project—stands for a new way \nforward in mobility. Our mission is to make it safe and easy for people and things \nto ...",
      "htmlSnippet":
          "Waymo—formerly the Google self-driving \u003cb\u003ecar\u003c/b\u003e project—stands for a new way \u003cbr\u003e\nforward in mobility. Our mission is to make it safe and easy for people and things \u003cbr\u003e\nto&nbsp;...",
      "cacheId": "jH6OCbvTOPQJ",
      "formattedUrl": "https://www.google.com/selfdrivingcar/",
      "htmlFormattedUrl":
          "https://www.google.com/selfdriving\u003cb\u003ecar\u003c/b\u003e/",
      "pagemap": {
        "cse_thumbnail": [
          {
            "src":
                "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQDe3q_ecCo3327WH9qZ7L8ws21NE7bS3jFwMQ03gCBs4uCnT6WVePFQPA",
            "width": "310",
            "height": "163"
          }
        ],
        "metatags": [
          {
            "og:image": "https://waymo.com/v2/static/images/waymo_banner.jpg",
            "og:type": "website",
            "twitter:card": "summary_large_image",
            "twitter:title": "Waymo", // Generated by https://quicktype.io
            "og:site_name": "Waymo",
            "og:title": "Waymo",
            "og:description":
                "Waymo—formerly the Google self-driving car project—stands for a new way forward in mobility. Our mission is to make it safe and easy for people and things to move around.",
            "twitter:creator": "@Waymo",
            "og:image:secure_url":
                "https://waymo.com/v2/static/images/waymo_banner.jpg",
            "twitter:image":
                "https://waymo.com/v2/static/images/waymo_banner.jpg",
            "referrer": "no-referrer",
            "twitter:site": "@Waymo",
            "viewport": "width=device-width, initial-scale=1.0",
            "twitter:description":
                "Waymo—formerly the Google self-driving car project—stands for a new way forward in mobility. Our mission is to make it safe and easy for people and things to move around.",
            "og:locale": "en",
            "og:url": "https://waymo.com/"
          }
        ],
        "cse_image": [
          {"src": "https://waymo.com/v2/static/images/waymo_banner.jpg"}
        ]
      }
    },
    {
      "kind": "customsearch#result",
      "title": "Google Car Search",
      "htmlTitle": "Google \u003cb\u003eCar\u003c/b\u003e Search",
      "link": "https://www.google.com/cars/",
      "displayLink": "www.google.com",
      "snippet":
          "Thank you for visiting Google.com/cars. The Google San Francisco Bay Area car \nsearch beta program has been discontinued as we focus on building the next ...",
      "htmlSnippet":
          "Thank you for visiting Google.com/\u003cb\u003ecars\u003c/b\u003e. The Google San Francisco Bay Area \u003cb\u003ecar\u003c/b\u003e \u003cbr\u003e\nsearch beta program has been discontinued as we focus on building the next&nbsp;...",
      "cacheId": "lCvPnLoDD5EJ",
      "formattedUrl": "https://www.google.com/cars/",
      "htmlFormattedUrl":
          "https://www.google.com/\u003cb\u003ecars\u003c/b\u003e/",
      "pagemap": {
        "metatags": [
          {"viewport": "initial-scale=1, minimum-scale=1, width=device-width"}
        ]
      }
    },
    {
      "kind": "customsearch#result",
      "title": "Send to Car Settings",
      "htmlTitle": "Send to \u003cb\u003eCar\u003c/b\u003e Settings",
      "link": "https://www.google.com/maps/sendtocar",
      "displayLink": "www.google.com",
      "snippet":
          "Send locations from Google to your car. Send addresses, businesses, and \ndirections from Google Maps to your Send to Car enabled vehicle or GPS device.",
      "htmlSnippet":
          "Send locations from Google to your \u003cb\u003ecar\u003c/b\u003e. Send addresses, businesses, and \u003cbr\u003e\ndirections from Google Maps to your Send to \u003cb\u003eCar\u003c/b\u003e enabled vehicle or GPS device.",
      "cacheId": "oObUH4fVm04J",
      "formattedUrl": "https://www.google.com/maps/sendtocar",
      "htmlFormattedUrl":
          "https://www.google.com/maps/sendto\u003cb\u003ecar\u003c/b\u003e"
    },
    {
      "kind": "customsearch#result",
      "title":
          "Cars.com, 300 S Riverside Plaza #1100, Chicago, IL, 60606, us ...",
      "htmlTitle":
          "\u003cb\u003eCars\u003c/b\u003e.com, 300 S Riverside Plaza #1100, Chicago, IL, 60606, us ...",
      "link":
          "https://www.google.com/maps/search/?api=1&query=Cars.com%2C+300+S+Riverside+Plaza+%231100%2C+Chicago%2C+IL%2C+60606%2C+us&query_place_id=ChIJv8wv1b0sDogRqn93AOSgVw4",
      "displayLink": "www.google.com",
      "snippet":
          "Cars.com, 300 S Riverside Plaza #1100, Chicago, IL, 60606, us. Your location. \nTrails. Dedicated lanes. Bicycle-friendly roads. Dirt/unpaved trails. Live traffic.",
      "htmlSnippet":
          "\u003cb\u003eCars\u003c/b\u003e.com, 300 S Riverside Plaza #1100, Chicago, IL, 60606, us. Your location. \u003cbr\u003e\nTrails. Dedicated lanes. Bicycle-friendly roads. Dirt/unpaved trails. Live traffic.",
      "cacheId": "xShVQ9sICD0J",
      "formattedUrl": "https://www.google.com/maps/search/?api=1...Cars...S...",
      "htmlFormattedUrl":
          "https://www.google.com/maps/search/?api=1...\u003cb\u003eCars\u003c/b\u003e...S...",
      "pagemap": {
        "cse_thumbnail": [
          {
            "src":
                "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQUDTMfgWSotdHvbOKW4AmY1steqsilnDJS4q33zGx-d0AXvvxPiFY9Mvs",
            "width": "204",
            "height": "247"
          }
        ],
        "metatags": [
          {
            "referrer": "origin",
            "twitter:card": "summary",
            "theme-color": "#3367D6",
            "viewport": "initial-scale=1.0, user-scalable=no",
            "google": "notranslate"
          }
        ],
        "cse_image": [
          {
            "src":
                "https://maps.gstatic.com/tactile/basepage/pegman_sherlock.png"
          }
        ]
      }
    },
    {
      "kind": "customsearch#result",
      "title":
          "Classic Cars West, 411 26th St, Oakland, CA, 94612, us - Google ...",
      "htmlTitle":
          "Classic \u003cb\u003eCars\u003c/b\u003e West, 411 26th St, Oakland, CA, 94612, us - Google ...",
      "link":
          "https://www.google.com/maps/search/?api=1&query=Classic+Cars+West%2C+411+26th+St%2C+Oakland%2C+CA%2C+94612%2C+us&query_place_id=ChIJucqhQauAj4ARZPrUnB0y67I",
      "displayLink": "www.google.com",
      "snippet":
          "Classic Cars West, 411 26th St, Oakland, CA, 94612, us. Your location. Trails. \nDedicated lanes. Bicycle-friendly roads. Dirt/unpaved trails. Live traffic. Fast. Slow\n.",
      "htmlSnippet":
          "Classic \u003cb\u003eCars\u003c/b\u003e West, 411 26th St, Oakland, CA, 94612, us. Your location. Trails. \u003cbr\u003e\nDedicated lanes. Bicycle-friendly roads. Dirt/unpaved trails. Live traffic. Fast. Slow\u003cbr\u003e\n.",
      "cacheId": "f7_EDhwOrDgJ",
      "formattedUrl":
          "https://www.google.com/maps/search/?api=1...Cars...411...",
      "htmlFormattedUrl":
          "https://www.google.com/maps/search/?api=1...\u003cb\u003eCars\u003c/b\u003e...411...",
      "pagemap": {
        "cse_thumbnail": [
          {
            "src":
                "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQUDTMfgWSotdHvbOKW4AmY1steqsilnDJS4q33zGx-d0AXvvxPiFY9Mvs",
            "width": "204",
            "height": "247"
          }
        ],
        "metatags": [
          {
            "referrer": "origin",
            "twitter:card": "summary",
            "theme-color": "#3367D6",
            "viewport": "initial-scale=1.0, user-scalable=no",
            "google": "notranslate"
          }
        ],
        "cse_image": [
          {
            "src":
                "https://maps.gstatic.com/tactile/basepage/pegman_sherlock.png"
          }
        ]
      }
    },
    {
      "kind": "customsearch#result",
      "title": "Street View photos come from two sources, Google and our ...",
      "htmlTitle":
          "Street View photos come from two sources, Google and our ...",
      "link": "https://www.google.com/streetview/explore/",
      "displayLink": "www.google.com",
      "snippet":
          "Where we're headed. We are driving through many countries with the Street View \ncar to bring you imagery that enhances your experience and helps you discover ...",
      "htmlSnippet":
          "Where we&#39;re headed. We are driving through many countries with the Street View \u003cbr\u003e\n\u003cb\u003ecar\u003c/b\u003e to bring you imagery that enhances your experience and helps you discover&nbsp;...",
      "cacheId": "8gJE30ywJMAJ",
      "formattedUrl": "https://www.google.com/streetview/explore/",
      "htmlFormattedUrl": "https://www.google.com/streetview/explore/",
      "pagemap": {
        "cse_thumbnail": [
          {
            "src":
                "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQX1cLnZUu-Z14c7gxGcW3xIlVMEd3eROiW7M7zCz3JXcLOe_GqP4QDRpvZ",
            "width": "310",
            "height": "163"
          }
        ],
        "metatags": [
          {
            "og:image":
                "https://lh3.googleusercontent.com/3wxVX9CvVROw7gEVATEnkFjrA8OcDsAVapJF30CDDZ9N59CcfiEVJzZKo4bK09csdyMTVBefdasBZemIfjEYOh6lQnS315OmlMCl=s0",
            "apple-itunes-app": "app-id=904418768",
            "twitter:title":
                "Street View photos come from two sources, Google and our contributors.",
            "twitter:card": "summary",
            "og:type": "article",
            "og:site_name": "Google Maps Street View",
            "og:title":
                "Street View photos come from two sources, Google and our contributors.",
            "og:description":
                "Learn about what Street View is, where we've been, and where we're going. To share Street View imagery, our engineering team is hard at work behind the scenes.",
            "twitter:image:src":
                "https://lh3.googleusercontent.com/peyT6rCarwklZzaRyoQV6x0yOxc5VcVDdG6scCjtLfUHs5jgBSuW09vgGkuB0Ij1mXefjB2Fb1cyOksIW6nqxWDd2-chCYvLFz9l=s0",
            "referrer": "no-referrer",
            "apple-mobile-web-app-status-bar-style": "black",
            "twitter:site": "@googlemaps",
            "viewport": "initial-scale=1, minimum-scale=1, width=device-width",
            "twitter:description":
                "Learn about what Street View is, where we've been, and where we're going. To share Street View imagery, our engineering team is hard at work behind the scenes.",
            "apple-mobile-web-app-capable": "yes"
          }
        ],
        "cse_image": [
          {
            "src":
                "https://lh3.googleusercontent.com/3wxVX9CvVROw7gEVATEnkFjrA8OcDsAVapJF30CDDZ9N59CcfiEVJzZKo4bK09csdyMTVBefdasBZemIfjEYOh6lQnS315OmlMCl=s0"
          }
        ]
      }
    },
    {
      "kind": "customsearch#result",
      "title":
          "Patent US48799 - Improvement in stake-holders for platform-cars ...",
      "htmlTitle":
          "Patent US48799 - Improvement in stake-holders for platform-\u003cb\u003ecars\u003c/b\u003e ...",
      "link": "http://www.google.com/patents/US48799",
      "displayLink": "www.google.com",
      "snippet":
          "The nature of my said invention consists in a novel mode of attaching and \nsecuring the stake to the side of a platform-car, whereby, while said stake is ...",
      "htmlSnippet":
          "The nature of my said invention consists in a novel mode of attaching and \u003cbr\u003e\nsecuring the stake to the side of a platform-\u003cb\u003ecar\u003c/b\u003e, whereby, while said stake is&nbsp;...",
      "formattedUrl": "www.google.com/patents/US48799",
      "htmlFormattedUrl": "www.google.com/patents/US48799",
      "pagemap": {
        "book": [
          {
            "image":
                "http://www.google.com/patents?id=&printsec=frontcover&img=1&zoom=1",
            "name":
                "Patent US48799 - Improvement in stake-holders for platform-cars",
            "description": "www.google.com",
            "url":
                "http://www.google.com/patents/US48799?utm_source=gb-gplus-share"
          }
        ],
        "metatags": [
          {
            "citation_patent_number": "US:48799",
            "og:image":
                "http://www.google.com/patents?id=&printsec=frontcover&img=1&zoom=1",
            "og:type": "book",
            "og:site_name": "Google Books",
            "dc.type": "Patent",
            "og:title":
                "Patent US48799 - Improvement in stake-holders for platform-cars",
            "dc.title": "Improvement in stake-holders for platform-cars",
            "dc.date": "1865-7-18",
            "og:url": "http://www.google.com/patents/US48799",
            "title":
                "Patent US48799 - Improvement in stake-holders for platform-cars",
            "dc.contributor": "Edwin A. Eddy"
          }
        ],
        "cse_image": [
          {
            "src":
                "http://www.google.com/patents?id=&printsec=frontcover&img=1&zoom=1"
          }
        ]
      }
    },
    {
      "kind": "customsearch#result",
      "title": "Magic Car Wash Express 2612 Washington Ave, Sheboygan, WI ...",
      "htmlTitle":
          "Magic \u003cb\u003eCar\u003c/b\u003e Wash Express 2612 Washington Ave, Sheboygan, WI ...",
      "link":
          "https://www.google.com/maps/search/?api=1&query=Magic%20Car%20Wash%20Express%202612%20Washington%20Ave%2C%20Sheboygan%2C%20WI%2053081%2C%20USA&query_place_id=ChIJKcX8Q_emBIgRmehDzYrbn7Q",
      "displayLink": "www.google.com",
      "snippet":
          "Magic Car Wash Express 2612 Washington Ave, Sheboygan, WI 53081, USA. \nYour location. Trails. Dedicated lanes. Bicycle-friendly roads. Dirt/unpaved trails.",
      "htmlSnippet":
          "Magic \u003cb\u003eCar\u003c/b\u003e Wash Express 2612 Washington Ave, Sheboygan, WI 53081, USA. \u003cbr\u003e\nYour location. Trails. Dedicated lanes. Bicycle-friendly roads. Dirt/unpaved trails.",
      "cacheId": "kqlP9js0yi8J",
      "formattedUrl":
          "https://www.google.com/.../search/?... Magic%20Car%20Wash%20Express%202612%20Washington%20Ave%2...",
      "htmlFormattedUrl":
          "https://www.google.com/.../search/?... Magic%20\u003cb\u003eCar\u003c/b\u003e%20Wash%20Express%202612%20Washington%20Ave%2...",
      "pagemap": {
        "cse_thumbnail": [
          {
            "src":
                "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQUDTMfgWSotdHvbOKW4AmY1steqsilnDJS4q33zGx-d0AXvvxPiFY9Mvs",
            "width": "204",
            "height": "247"
          }
        ],
        "metatags": [
          {
            "referrer": "origin",
            "twitter:card": "summary",
            "theme-color": "#3367d6",
            "viewport": "initial-scale=1.0, user-scalable=no",
            "google": "notranslate"
          }
        ],
        "cse_image": [
          {
            "src":
                "https://maps.gstatic.com/tactile/basepage/pegman_sherlock.png"
          }
        ]
      }
    },
    {
      "kind": "customsearch#result",
      "title": "Google.org brings the best of Google to help solve some of ...",
      "htmlTitle":
          "Google.org brings the best of Google to help solve some of ...",
      "link": "https://www.google.com/giving/",
      "displayLink": "www.google.com",
      "snippet":
          "Learn how Google.org uses the best of Google to help nonprofits and social \nenterprises solve humanity's biggest challenges.",
      "htmlSnippet":
          "Learn how Google.org uses the best of Google to help nonprofits and social \u003cbr\u003e\nenterprises solve humanity&#39;s biggest challenges.",
      "cacheId": "i3IgMGM5SwIJ",
      "formattedUrl": "https://www.google.com/giving/",
      "htmlFormattedUrl": "https://www.google.com/giving/",
      "pagemap": {
        "cse_thumbnail": [
          {
            "src":
                "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQHLsk2LGw-p6iYNTPiAUIhF3sekuEn9hpRKNWLPmjb7Ct5RYEBl52STC4",
            "width": "310",
            "height": "163"
          }
        ],
        "metatags": [
          {
            "og:image":
                "https://lh3.googleusercontent.com/1kA4d6Jn-j_5ByaplDmw4MX1-T8lZAWOO7kKop8Mmu1-sA9lnVMN8Bn65KeF9JLVpkxDNdGkHAO8H3RIrO-a3kMRpxIX2pdPqz7U-A=w1200-l80-sg-rj",
            "og:type": "website",
            "og:site_name": "Google.org",
            "viewport": "width=device-width, initial-scale=1",
            "og:title":
                "Google.org brings the best of Google to help solve some of humanity’s biggest challenges — combining funding, innovation, and technical expertise to support underserved communities and provide opportunity for everyone.",
            "og:locale": "root",
            "og:url": "https://google.org/",
            "og:description":
                "Learn how Google.org uses the best of Google to help nonprofits and social enterprises solve humanity’s biggest challenges."
          }
        ],
        "cse_image": [
          {
            "src":
                "https://lh3.googleusercontent.com/1kA4d6Jn-j_5ByaplDmw4MX1-T8lZAWOO7kKop8Mmu1-sA9lnVMN8Bn65KeF9JLVpkxDNdGkHAO8H3RIrO-a3kMRpxIX2pdPqz7U-A=w1200-l80-sg-rj"
          }
        ]
      }
    },
    {
      "kind": "customsearch#result",
      "title":
          "Grand Prix Car Wash 1295 U.S. Hwy 395 N, Gardnerville, NV 89410 ...",
      "htmlTitle":
          "Grand Prix \u003cb\u003eCar\u003c/b\u003e Wash 1295 U.S. Hwy 395 N, Gardnerville, NV 89410 ...",
      "link":
          "https://www.google.com/maps/search/?api=1&query=Grand%20Prix%20Car%20Wash%201295%20U.S.%20Hwy%20395%20N%2C%20Gardnerville%2C%20NV%2089410%2C%20USA&query_place_id=ChIJTXR9ko--mYARgqNEakuXA8k",
      "displayLink": "www.google.com",
      "snippet":
          "Grand Prix Car Wash 1295 U.S. Hwy 395 N, Gardnerville, NV 89410, USA. Your \nlocation. Trails. Dedicated lanes. Bicycle-friendly roads. Dirt/unpaved trails.",
      "htmlSnippet":
          "Grand Prix \u003cb\u003eCar\u003c/b\u003e Wash 1295 U.S. Hwy 395 N, Gardnerville, NV 89410, USA. Your \u003cbr\u003e\nlocation. Trails. Dedicated lanes. Bicycle-friendly roads. Dirt/unpaved trails.",
      "cacheId": "ikBVfMiIDK0J",
      "formattedUrl":
          "https://www.google.com/.../search/?... Grand%20Prix%20Car%20Wash%201295%20U...",
      "htmlFormattedUrl":
          "https://www.google.com/.../search/?... Grand%20Prix%20\u003cb\u003eCar\u003c/b\u003e%20Wash%201295%20U...",
      "pagemap": {
        "cse_thumbnail": [
          {
            "src":
                "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQUDTMfgWSotdHvbOKW4AmY1steqsilnDJS4q33zGx-d0AXvvxPiFY9Mvs",
            "width": "204",
            "height": "247"
          }
        ],
        "metatags": [
          {
            "referrer": "origin",
            "twitter:card": "summary",
            "theme-color": "#3367D6",
            "viewport": "initial-scale=1.0, user-scalable=no",
            "google": "notranslate"
          }
        ],
        "cse_image": [
          {
            "src":
                "https://maps.gstatic.com/tactile/basepage/pegman_sherlock.png"
          }
        ]
      }
    }
  ]
};